###
GET http://localhost:3000
###
//users queries
GET http://localhost:3000/users   
###
GET  http://localhost:3000/users/1  
###
post http://localhost:3000/users
Content-Type: application/json

{
 "full_name":"max",
 "email":"maximas@gmail.com",
 "contact_phone":"0743",
 "address":"123"
 
}

###
PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "contact_phone":12345
}

###
DELETE http://localhost:3000/users/4

//vehicle queries
###
GET http://localhost:3000/vehicles

###
GET http://localhost:3000/vehicle/1
###
POST http://localhost:3000/vehicles
Content-Type: application/json

{
    "owner_id": 1,
    "make":"nissan",
    "model":"teana",
    "year": 2021,
    "vin":"12335",
    "status":"available",
    "price":128934.23,
    "mileage":10000,
    "fuel_type":"diesel",
    "location": "eldoret"
}

###
PUT http://localhost:3000/vehicles/1
Content-Type: application/json

{
    "status":"sold"
}

###
DELETE http://localhost:3000/vehicles/1
//location queries
###
GET http://localhost:3000/location
###
get http://localhost:3000/location/eldoret
###
POST http://localhost:3000/location
Content-Type: application/json

{
    "name_of_branch":"eldoret branch",
    "city":"nairobi",
    "address":"eldoret",
    "country":"Kenya",
    "zip_code":"00100"
}
###
PUT http://localhost:3000/location/eldoret
Content-Type: application/json

{
    "zip_code":"00200"
}
###
DELETE http://localhost:3000/location/1234

//bookings queries
###
GET http://localhost:3000/bookings
###
GET http://localhost:3000/bookings/1
###
POST http://localhost:3000/bookings
Content-Type: application/json

{
    "property_type":"vehicle",
    "property_id":1,
    "total_amount":10000,
    "user_id":1,
    "status":"pending",
    "location":"eldoret"
}

###
put http://localhost:3000/bookings/2
Content-Type: application/json
    
    {
        "status":"approved"
    }
###
DELETE http://localhost:3000/bookings/1

//payments queries
###
GET http://localhost:3000/payments
###
GET http://localhost:3000/payments/1
###
POST http://localhost:3000/payments
Content-Type: application/json

{
    "property_type":"vehicle",
    "property_id":1,
    "amount":10000,
    "booking_id":1,
    "buyer_id":1,
    "status":"pending",
    "payment_method":"mpesa",
    "transaction_id":"12345"
}
###
PUT http://localhost:3000/payments/1
Content-Type: application/json

{
    "status":"approved"
}
###
DELETE http://localhost:3000/payments/1