###
GET http://localhost:3000

//register queries
###
POST http://localhost:3000/register
Content-Type: application/json

{
    "username":"daniel",
    "password":"pass",
    "role":"user",
    "email":"daniel@gmail.com",
    "address":"1234 Main St, City, State, 12345",
    "contact_phone":"1234567890"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{    
    "username":"daniel",
    "role":"user",
    "password":"pass"
}
    
    
###
//users queries
GET http://localhost:3000/users   
###
GET  http://localhost:3000/users/21  
###
post http://localhost:3000/users
Content-Type: application/json

{
 "full_name":"max",
 "email":"maximass@gmail.com",
 "contact_phone":"0743",
 "address":"123"
 
}

###
PUT http://localhost:3000/users/21
Content-Type: application/json

{
    "contact_phone":12345
}

###
DELETE http://localhost:3000/users/4

//vehicle queries
###
GET http://localhost:3000/vehicles

###
GET http://localhost:3000/vehicle/1
###
POST http://localhost:3000/vehicles
Content-Type: application/json

{
    "make":"nissan",
    "model":"teana",
    "year": 2021,
    "vin":"12865675",
    "status":"available",
    "price":128934.23,
    "mileage":10000,
    "fuel_type":"diesel",
    "location": "eldoret",
    "images":[
        "https://i.pinimg.com/236x/3e/0a/56/3e0a56392a2588fd70dbe71b63951f16.jpg",
        "https://i.pinimg.com/236x/0a/6b/1e/0a6b1e51a55186aed93c30ae491bddd3.jpg",
        "https://i.pinimg.com/236x/dd/8a/b6/dd8ab68cd072b00eed72eaf29d14d855.jpg",
        "https://i.pinimg.com/236x/ed/e5/85/ede5859dac368665c0fc0092485f8024.jpg"
    ]
}

###
PUT http://localhost:3000/vehicles/5
Content-Type: application/json

{
    "images":[
        "https://i.pinimg.com/236x/3e/0a/56/3e0a56392a2588fd70dbe71b63951f16.jpg",
        "https://i.pinimg.com/236x/0a/6b/1e/0a6b1e51a55186aed93c30ae491bddd3.jpg",
        "https://i.pinimg.com/236x/dd/8a/b6/dd8ab68cd072b00eed72eaf29d14d855.jpg",
        "https://i.pinimg.com/236x/ed/e5/85/ede5859dac368665c0fc0092485f8024.jpg"
    ]
}

###
DELETE http://localhost:3000/vehicles/1
###

GET http://localhost:3000/vehicleshistory
//vehiclesHistory queries
###
GET http://localhost:3000/vehiclesHistory
###
GET http://localhost:3000/vehiclesHistory/1
###
POST http://localhost:3000/vehiclesHistory
Content-Type: application/json

{
    
    "property_id":9,
    "previous_owner":"max",
    "transfer_date":"2021-09-09",
    "maintenance_type":"service",
    "maintenance_date":"2021-09-09",
    "service_provider":"max",
    "maintenance_cost":10000,
    "tenant_name":"max",
    "lease_start":"2021-09-09",
    "lease_end":"2021-09-09",
    "usage_type":"rental",
    "tax_payment_date":"2021-09-09",
    "tax_amount":10000,
    "legal_issue":"none",
    "resolution_date":"2021-09-09",
    "permit_approval_date":"2021-09-09",
    "disaster_type":"fire",
    "disaster_description":"fire",
    "disaster_date":"2021-09-09",
    "status_after_disaster":"sold",
    "environmental_assessment_date":"2021-09-09",
    "insurance_policy_number":"12345",
    "claim_amount":10000,
    "claim_date":"2021-09-09",
    "crime_type":"theft",
    "crime_date":"2021-09-09",
    "valuation_date":"2021-09-09",
    "property_value":10000,
    "dispute_type":"none",
    "dispute_status":"resolved",
    "dispute_resolution_date":"2021-09-09"
    
}
###
PUT http://localhost:3000/vehiclesHistory/1
Content-Type: application/json

{
    "status_after_disaster":"available"
}
###
DELETE http://localhost:3000/vehiclesHistory/1



//location queries
###
GET http://localhost:3000/location
###
get http://localhost:3000/location/eldoret
###
POST http://localhost:3000/location
Content-Type: application/json

{
    "name_of_branch":"eldoret branch",
    "city":"nairobi",
    "address":"eldoret",
    "country":"Kenya",
    "zip_code":"00100"
}
###
PUT http://localhost:3000/location/eldoret
Content-Type: application/json

{
    "zip_code":"00200"
}
###
DELETE http://localhost:3000/location/1234

//bookings queries
###
GET http://localhost:3000/bookings
###
GET http://localhost:3000/bookings/1
###
POST http://localhost:3000/bookings
Content-Type: application/json

{
    "property_type":"vehicle",
    "property_id":1,
    "total_amount":10000,
    "user_id":1,
    "status":"pending",
    "location":"eldoret"
}

###
put http://localhost:3000/bookings/2
Content-Type: application/json
    
    {
        "status":"approved"
    }
###
DELETE http://localhost:3000/bookings/1

//payments queries
###
GET http://localhost:3000/payments
###
GET http://localhost:3000/payments/1
###
POST http://localhost:3000/payments
Content-Type: application/json

{
    "property_type":"vehicle",
    "property_id":1,
    "amount":10000,
    "booking_id":1,
    "buyer_id":1,
    "status":"pending",
    "payment_method":"mpesa",
    "transaction_id":"12345"
}
###
PUT http://localhost:3000/payments/1
Content-Type: application/json

{
    "status":"approved"
}
###
DELETE http://localhost:3000/payments/1

//Houses queries
###
GET http://localhost:3000/houses
###
GET http://localhost:3000/houses/1
###
POST http://localhost:3000/houses
Content-Type: application/json

{
    
    "address":"eldoret",
    "name":"max",
    "number_of_rooms":3,
    "size":100,
    "price":10000,
    "status":"available",
    "year_built":2021,
    "images":[
        "https://i.pinimg.com/236x/08/8d/cc/088dcce619dc0b04573aacfe40ffe288.jpg",
        "https://i.pinimg.com/736x/2f/7b/fd/2f7bfd22c1f1f6bd4287ca397ba1e9b8.jpg",
        "https://i.pinimg.com/236x/f5/dc/d8/f5dcd801f5a563d294c37c0ab708e35f.jpg",
        "https://i.pinimg.com/236x/47/0a/f9/470af9362057e14e2bdc9d3f4778956e.jpg"
    ]

}
###
PUT http://localhost:3000/houses/1
Content-Type: application/json

{
    "images":[
        "https://i.pinimg.com/236x/08/8d/cc/088dcce619dc0b04573aacfe40ffe288.jpg",
        "https://i.pinimg.com/736x/2f/7b/fd/2f7bfd22c1f1f6bd4287ca397ba1e9b8.jpg",
        "https://i.pinimg.com/236x/f5/dc/d8/f5dcd801f5a563d294c37c0ab708e35f.jpg",
        "https://i.pinimg.com/236x/47/0a/f9/470af9362057e14e2bdc9d3f4778956e.jpg"
    ]
}
###
DELETE http://localhost:3000/houses/1


//houses history queries
###
GET http://localhost:3000/houseHistory
###
GET http://localhost:3000/houseHistory/1
###
POST http://localhost:3000/houseHistory
Content-Type: application/json

{    
    "property_id":1,
    "previous_owner":"max",
    "transfer_date":"2021-09-09",
    "maintenance_type":"service",
    "maintenance_date":"2021-09-09",
    "service_provider":"max",
    "maintenance_cost":10000,
    "tenant_name":"max",
    "lease_start":"2021-09-09",
    "lease_end":"2021-09-09",
    "usage_type":"rental",
    "legal_issues":"none",
    "resolution_date":"2021-09-09",
    "permit_approval_date":"2021-09-09",
    "disaster_type":"fire",
    "disaster_description":"fire",
    "disaster_date":"2021-09-09",
    "status_after_disaster":"sold",
    "environmental_assessment_date":"2021-09-09",
    "insurance_policy_number":"12345",
    "claim_amount":10000,
    "claim_date":"2021-09-09",
    "crime_type":"theft",
    "crime_date":"2021-09-09",
    "valuation_date":"2021-09-09",
    "property_value":10000,
    "utility_type":"electricity",
    "utility_installation_amount":10000,
    "utility_installation_date":"2021-09-09",
    "infrastructure_update_date":"2021-09-09",
    "dispute_type":"none",
    "dispute_status":"resolved",
    "dispute_resolution_date":"2021-09-09",
    "tenant_feedback":"good",
    "feedback_date":"2021-09-09",
    "construction_date":"2021-09-09",
    "renovation_date":"2021-09-09"
}

###
PUT http://localhost:3000/houseHistory/1
Content-Type: application/json

{
    "status_after_disaster":"available"
}
###
DELETE http://localhost:3000/houseHistory/1

//land queries
###
GET http://localhost:3000/lands
###
GET http://localhost:3000/lands/1
###
POST http://localhost:3000/lands
Content-Type: application/json

{
    "location":"eldoret",
    "size":100,
    "price":10000,
    "status":"available",
    "land_type":"commercial",
    "images":[
        "https://res.cloudinary.com/demo/image/upload/v1623456789/renovation1.jpg",
        "https://res.cloudinary.com/demo/image/upload/v1623456789/renovation2.jpg"
    ]
}
###
PUT http://localhost:3000/lands/2
Content-Type: application/json

{
    "images":[
        "https://i.pinimg.com/236x/ac/1f/65/ac1f657fd8bb7ee744e678485745de63.jpg",
        "https://i.pinimg.com/736x/7a/76/1d/7a761d0c69df3858fceff11ef8708f48.jpg",
        "https://i.pinimg.com/236x/73/93/c0/7393c077d7cbe8f7e79b7aba9389c94e.jpg",
        "https://i.pinimg.com/236x/ec/35/56/ec35562d5528acc21faa961d80433694.jpg",
        "https://i.pinimg.com/236x/76/41/85/76418554a92e73173ffe28608e65f45d.jpg"
    ]
}

###
DELETE http://localhost:3000/lands/1

//landHistory queries
###
GET http://localhost:3000/landHistory
###
GET http://localhost:3000/landHistory/1
###
POST http://localhost:3000/landHistory
Content-Type: application/json

{
    "property_type":"land",
    "property_id":2,
    "previous_owner":"max",
    "transfer_date":"2021-09-09",
    "tenant_name":"max",
    "lease_start":"2021-09-09",
    "lease_end":"2021-09-09",
    "legal_issues":"none",
    "resolution_date":"2021-09-09",
    "permit_approval_date":"2021-09-09",
    "disaster_type":"fire",
    "disaster_description":"fire",
    "disaster_date":"2021-09-09",
    "status_after_disaster":"sold",
    "environmental_assessment_date":"2021-09-09",
    "crime_type":"theft",
    "crime_date":"2021-09-09",
    "valuation_date":"2021-09-09",
    "property_value":10000,
    "dispute_type":"none",
    "dispute_status":"resolved",
    "dispute_resolution_date":"2021-09-09",
    "tenant_feedback":"good",
    "feedback_date":"2021-09-09"
}
###
PUT http://localhost:3000/landHistory/2
Content-Type: application/json

{
    "status_after_disaster":"available"
}
###
DELETE http://localhost:3000/landHistory/2

//reviews queries
###
GET http://localhost:3000/reviews
###
GET http://localhost:3000/reviews/1
###
POST http://localhost:3000/reviews
Content-Type: application/json

{
    "property_type":"vehicle",
    "property_id":1,
    "user_id":1,
    "rating":5,
    "comment":"good"
}
###
PUT http://localhost:3000/reviews/1
Content-Type: application/json

{
    "rating":4
}
###
DELETE http://localhost:3000/reviews/1